apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-vault-sidecar
  namespace: app-vault-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-vault-sidecar
  template:
    metadata:
      labels:
        app: app-vault-sidecar
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app-role"
        vault.hashicorp.com/agent-inject-secret-db.txt: "database/creds/appdb-role"
        vault.hashicorp.com/agent-inject-template-db.txt: |
          {{- with secret "database/creds/appdb-role" -}}
          username={{ .Data.username }}
          password={{ .Data.password }}
          {{- end -}}
    spec:
      serviceAccountName: app-sa
      containers:
        - name: app
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
              cat /vault/secrets/db.txt
              sleep 50
              done
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"