apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-vault-secret
  namespace: app-vault-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-vault-secret
  template:
    metadata:
      labels:
        app: app-vault-secret
    spec:
      serviceAccountName: app-sa
      containers:
        - name: app
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "$APP_USERNAME"
                echo "$APP_PASSWORD"
                sleep 100
              done
          env:
            - name: APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: username
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: password
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
