apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-config
  namespace: app-vault-demo
spec:
  type: kv-v2
  mount: secret
  path: app/config
  destination:
    name: app-config
    create: true
  refreshAfter: 30s
  vaultAuthRef: vault-auth
